### ISSUE TITLE
why u use pair in redux?

### ISSUE THREAD

**Issue by martinupset** [hondahmd/JSA-Mentorship-Honda#1] opened 2020-01-16 11:14 UTC
fuck, I try to use your code but I find u create a crazy fn in redux, I don't like it. If you are good at coding, plz make your code easy to copy

**Comment by hondahmd** [comment] 2020-01-17 04:19
Just personal likes, I prefer key-value but not switch-case, they're the same in the end, you can use your way to implement. Since it's not a bug, closing it.

**Closed as completed** 2020-01-17 04:19 UTC
